CREATE UNIQUE INDEX IF NOT EXISTS uq_patient_document_active
ON TPATIENTS (VL_DOCUMENT)
WHERE IN_DELETED = false;

CREATE UNIQUE INDEX IF NOT EXISTS uq_doctor_credential_active
ON TDOCTORS (VL_CREDENTIAL)
WHERE IN_DELETED = false;