CREATE UNIQUE INDEX IF NOT EXISTS uq_persons_user_active
ON TPERSONS (ID_USER)
WHERE IN_DELETED = false;

CREATE UNIQUE INDEX IF NOT EXISTS uq_persons_document_active
ON TPERSONS (VL_DOCUMENT)
WHERE IN_DELETED = false;

CREATE UNIQUE INDEX IF NOT EXISTS uq_patient_person_active
ON TPATIENTS (ID_PERSON)
WHERE IN_DELETED = false;

CREATE UNIQUE INDEX IF NOT EXISTS uq_doctor_credential_active
ON TDOCTORS (VL_CREDENTIAL)
WHERE IN_DELETED = false;

CREATE UNIQUE INDEX IF NOT EXISTS uq_doctor_person_active
ON TDOCTORS (ID_PERSON)
WHERE IN_DELETED = false;